Added javadoc
11cfif/spsuace-hello-world pull request #10
Opened 2019-02-20 17:02 UTC by NicolayGeorgiev

2019-02-21 08:42 UTC, 11cfif requested changes

2019-02-21 08:42 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +            temp = x2;
можно в одну строчку

2019-02-21 08:42 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +        return (float) Math.pow(Math.pow((x2 - x1), 2) + Math.pow((y2 - y1), 2), 0.5);
есть функция корня в том же классе,

2019-03-02 16:02 UTC, NicolayGeorgiev commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +            temp = x2;
Исправил

2019-03-02 16:03 UTC, NicolayGeorgiev commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +        return (float) Math.pow(Math.pow((x2 - x1), 2) + Math.pow((y2 - y1), 2), 0.5);
Исправил

2019-03-09 22:20 UTC, closed without merging