task1
11cfif/spsuace-hello-world pull request #4
Opened 2019-02-15 20:17 UTC by hBuzzy

Added javadoc

2019-02-15 20:30 UTC, hBuzzy commented
Added javadoc

2019-02-16 07:09 UTC, 11cfif commented
![image](https://user-images.githubusercontent.com/1713952/52896001-d8b2cb00-31d2-11e9-917e-c6726b3765e8.png)
Очень странный комментарий к PullRequest-у :)

2019-02-16 07:30 UTC, 11cfif requested changes

2019-02-16 07:30 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +        if(x1 < x2)
в java не принято переносить скобочки на другую строку после методов и операторов. Это разрывает код

2019-02-16 07:30 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +        float length = (float)Math.sqrt
Господи :) 
Не надо так делать. У вас Идея черточкой пишет границу максимальной длины символов в строке. Она обычно около 120 символов. Тут бы все влезло. Но даже если бы не влезло, в Java обычно переносят без скобок. Т. е. это бы выглядело бы так
```java
    float length = (float) Math.sqrt(
            Math.pow((x2 - x1), 2) + (Math.pow((y2 - y1), 2)));
```
Закрывающие скобочки иногда переносятся вниз, но это редко и обычно в очень специфичных случаях при большой вложенности. И да, у вас тут в лишние скобки второе слагаемое взято

2) После запятой тоже надо ставить пробел Math.pow((y2 - y1), 2)

2019-02-16 07:30 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        for (int i = 1; i <= n; i++){num += i;}
никогда так не делайте в java 
все видят цикл и интуитивно смотрят вниз, чтобы посмотреть на тело цикла. не надо экономить строчки

2019-02-16 07:30 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        if(top >= height)
1) пробел после if
2) не забываем фигурные скобочки
```java
    if (top >= height) {
        doAction();
    } else {
        doAction2();
    }
```
Это обязательное условие, потому что, когда вам надо будет добавить еще одну строчку в тело, вам придется проставлять скобочки все равно (java не python, она без скобок умеет только одну строку понимать под телом)

2019-02-16 07:30 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        else
этот else уже не нужен, так как если мы попадем в одну из веток выше, то мы точно выйдем из метода, значит до этих строк уже не дойдем. 
Лишнюю вложенность лучше убирать, если это не мешает чтению. Тут два предыдущих условия рядом, поэтому чтению это не мешает, мы сразу видим что выше везде return и поэтому вложенность не нужна

2019-02-16 07:30 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +                    continue;
1) тут можно сделать break и тогда мы сразу выйдем из цикла, а не будем проверять повторно условие height > position в while-е
2) зачем писать дважды days++ если можно один раз перед условием

2019-02-16 07:30 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +            {
не надо переносить скобочки

2019-02-16 07:30 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        for(int i =1; i <= n; i++) {factorial *= i;}
как писал выше, после for пробел, само тело на следующую строчку

2019-02-16 09:08 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/MainTask.java
> +    public static void main(String[] args) {
Это задание зачтено

2019-02-16 09:09 UTC, 11cfif commented
Сделайте еще так, чтобы MainTest проходил

2019-02-16 10:39 UTC, 11cfif requested changes

2019-02-16 10:39 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +        if (x1 < x2){
пробел перед {

2019-02-16 10:39 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +    {
скобка не тут

2019-02-16 10:39 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        for (int i = 1; i <= n; i++){
пробел перед {

2019-02-16 10:41 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/Main.java
> +        return "Hello world! I am a first program";
Зачтено

2019-02-16 10:41 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +
зачтено

2019-02-16 10:41 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
>      }
зачтено

2019-02-16 10:41 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        return factorial;
зачтено

2019-02-16 10:42 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +            if(position >= height){
пробелы (целых 2)

2019-02-16 10:49 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
>          return x1 + ", " + x2;
Зачтено

2019-02-16 10:49 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +
зачтено

2019-02-16 10:50 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        }
зачтено

2019-03-09 22:22 UTC, closed without merging