Java task v.1.0
11cfif/spsuace-hello-world pull request #6
Opened 2019-02-16 13:36 UTC by 6Naci

2019-02-16 13:42 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        System.out.println(sum(5)); //Проверка первого задания
У вас же есть тесты :) 
Вы там проверяли свой код? 
Плюс для себя вы там смело можете добавить еще тестов.

2019-02-16 13:43 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +
очень много пустых строк, обычно ими отделяют разные смысловые части, тут это явно лишнее

2019-02-16 13:44 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +            if (day > 0) {
Элегантное решение :)

2019-02-16 13:49 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        //int N = String.valueOf(Math.abs(n)).length(); //Количество разрядов в числе
А что вы дальше не развили этот вариант? Я бы накинул бал за хитрость)

2019-02-16 13:50 UTC, 6Naci commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        System.out.println(sum(5)); //Проверка первого задания
Я сначала их не увидел, пришлось создать main)

2019-02-16 13:58 UTC, hBuzzy commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        //int N = String.valueOf(Math.abs(n)).length(); //Количество разрядов в числе
А я думал, что подобная хитрость будет караться. Пришлось без нее обойтись)) Учтем)

2019-02-16 13:59 UTC, 11cfif requested changes

2019-02-16 13:59 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +            result /= (int) Math.pow(10, i - 1);
очень сложно, по сути ваши итерации не имею смысла, а имеет смысл только одна последняя

2019-02-16 14:03 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        //int N = String.valueOf(Math.abs(n)).length(); //Количество разрядов в числе
Ну это будет от обстоятельств зависеть. 
Караться это точно не будет, максимум попрошу написать нормально. Здесь единственная причина, почему так не стоит делать, то что класс String мы не проходили. Но так как это задание не на закрепление материала, а просто разминка, то тут это бы прокатило)

2019-02-16 14:08 UTC, 11cfif commented
Поправьте решение задачи с разрядами (но только уже не через строку) 
Все остальное я зачел

2019-02-16 14:11 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        System.out.println(sum(5)); //Проверка первого задания
Удалите теперь, чтобы не мешалось вам же в будущем

2019-02-17 06:04 UTC, 11cfif requested changes

2019-02-17 06:04 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        int result = 0;
пробел + слишком много лишнего. Можно сразу вернуть формулу или убрать лишнюю инициализию нулем

2019-02-17 08:38 UTC, 6Naci commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        int result = 0;
Хорошо, сейчас исправлю. У меня возник вопрос, при одновременном объявлении и инициализации переменной IDEA недовольна и мне пришлось лишней строкой сначала инициализировать нулем, с чем это связано?

2019-02-17 08:59 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        int result = 0;
Не понял что ей не нравилось. Для такого кода - все ок
`int result = Math.abs((n % (int)Math. pow(10, order))/(int)Math. pow(10, order - 1));`

2019-02-17 09:02 UTC, 6Naci commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        int result = 0;
![image](https://user-images.githubusercontent.com/47646069/52910667-e5efb880-32ab-11e9-8424-d4b252215d04.png)

2019-02-17 09:04 UTC, 6Naci commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        int result = 0;
Подсвечивает, что локальная переменная избыточна

2019-02-17 09:06 UTC, 6Naci commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        int result = 0;
Я посмотрел в интернете, IDEA сама подсказывает, что код можно улучшить и инициализация лишняя

2019-02-17 09:11 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        int result = 0;
Я думал у вас прям красным подчеркивает. Да, идея умная, она часто подсказывает как можно улучшить код. Но не всегда надо следовать ее подсказкам, иногда лучше реально создать переменную с понятным названием, чтобы при чтении кода сразу было понятно что это такое. Но это не тот случай

2019-02-17 09:11 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        int result = 0;
P.S. в винде есть замечательная программка ножницы, для маленьких скриншотов экрана

2019-03-09 22:22 UTC, closed without merging