Task 1
11cfif/spsuace-hello-world pull request #9
Opened 2019-02-20 00:45 UTC by Lenaami

Done

2019-02-20 07:02 UTC, 11cfif requested changes

2019-02-20 07:02 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +        double x1 = (-b + Math.sqrt(Math.pow(b, 2) - 4 * a * c)) / (2 * a);
В принципе можно в переменную выделить, чтобы код не дублировать

2019-02-20 07:02 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        for (int i = 1; ; i++) {
хитро)

2019-02-20 07:02 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        for (int i = 1; i <= order; i++) {
а почему нельзя просто возвести в нужную степень? В классе Math есть нужные методы

2019-02-20 14:38 UTC, Lenaami commented on src/main/java/ru/spsuace/helloworld/task1/DoubleTask.java
> +        double x1 = (-b + Math.sqrt(Math.pow(b, 2) - 4 * a * c)) / (2 * a);
Добавила переменную с корнем дискриминанта

2019-02-20 14:39 UTC, Lenaami commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        for (int i = 1; i <= order; i++) {
Забыла, что можно преобразовать в int) Сделала через pow

2019-02-21 08:44 UTC, 11cfif commented on src/main/java/ru/spsuace/helloworld/task1/IntegerTask.java
> +        return Sum;
на будущее, не пишите переменные с большой буквы. с большой буквы пишутся только имена классов

2019-03-09 22:20 UTC, closed without merging